//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Changes CDO for Customer.
///    @author lichong
///    @date 2024/3/28
///
namespace CamstarServiceClient.Service {
    
    public class CustomerChanges : NamedDataObjectChanges {
        public string Company {
            get; set;
        }
        public string Name
        {
            get; set;
        }
        public string Notes
        {
            get; set;
        }

        public string Description
        {
            get; set;
        }
        public string Country {
            get; set;
        }
        public string WebSite {
            get; set;
        }
        public string PhoneNumber {
            get; set;
        }
        public string AddressLine1 {
            get; set;
        }
        public string AddressLine2 {
            get; set;
        }
        public string City {
            get; set;
        }
        public string State {
            get; set;
        }
    }
}
