//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Changes CDO for Customer.
///    @author lichong
///    @date 2024/3/28
///
namespace CamstarServiceClient.Service {
    
    public class VendorChanges : NamedDataObjectChanges {
        public string Name
        {
            get; set;
        }
        public string Notes
        {
            get; set;
        }

        public string Description
        {
            get; set;
        }
        public ICollection<VendorItemChanges> VendorItems { get; set; }
    }
}
