//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///     @author lichong\n    @date 2024/3/25
///
namespace CamstarService.ServiceContent {
    
    public class ProductRef : RevisionedObject {
        public ProductRef(string name, string revision, bool useROR) : base(name, revision, useROR) { }
        public ProductRef(string name, string revision) : base(name, revision, false) { }
        public ProductRef(string name) : base(name, null, true) { }
    }
}
