//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///     @author lichong\n    @date 2024/3/25
///
namespace CamstarService.ServiceContent {

    public class StepRef : NamedSubentity
    {
        public StepRef(string name) : base(name)
        {
        }
    }
}
