//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Start is used to create a container or a multi-level container structure.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarService.ServiceContent {
    
    public class ContainerAttrMaint : ContainerTxn {
        public ICollection<ContainerAttrDetail>? ServiceDetails
        {
            get; set;
        }

    }
}
