//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Changes CDO for Product.
///    @author lichong
///    @date 2024/3/28
///
namespace CamstarServiceClient.Service {
    
    public class ProductChanges : RevisionedObjectChanges {
        public CustomerRef Customer {
            get; set;
        }
        public string CustomerProductNumber {
            get; set;
        }
        public ProductFamilyRef ProductFamily {
            get; set;
        }
        public ProductTypeRef ProductType {
            get; set;
        }
        public UOMRef StdStartUOM {
            get; set;
        }
        public WorkflowRef Workflow {
            get; set;
        }
        public System.Nullable<double> StdStartQty {
            get; set;
        }
        public string Name {
            get; set;
        }
        public UOMRef UOM {
            get; set;
        }
        public System.Nullable<bool> MfgOrderRequired {
            get; set;
        }
        public StartReasonRef StdStartReason {
            get; set;
        }
        public ContainerLevelRef StdStartLevel {
            get; set;
        }
        public OwnerRef StdStartOwner {
            get; set;
        }
        public string Revision {
            get; set;
        }
        public string Description { get; set; }
    }
}
