//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description This is used to group non-persistent subentities containing service related data.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarService.ServiceContent {
    
    public abstract class ServiceData : Subentity {
    }
}
