//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Services that update the status of resources. Resource transactions always write out history information.
///    @author lichong
///    @date 2024/3/26
///
namespace CamstarService.ServiceContent {
    
    public abstract class ResourceTxn : ShopFloor {
    }
}
