//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description StartDetails describes the attributes of the container about to be started.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarServiceClient.Service {
    
    public class StartDetails : ServiceDetails {
        public OwnerRef Owner {
            get; set;
        }
        public MfgOrderRef MfgOrder {
            get; set;
        }
        public StartReasonRef StartReason {
            get; set;
        }
        public ProductRef Product {
            get; set;
        }
        public System.Nullable<double> Qty {
            get; set;
        }
        public CustomerRef Customer {
            get; set;
        }
        public ContainerStatusEnum? Status {
            get; set;
        }
        public ContainerLevelRef Level {
            get; set;
        }
        public string ContainerName {
            get; set;
        }
        public System.Nullable<bool> AutoNumber {
            get; set;
        }
    }
}
