//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Named Subentity
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarServiceClient.Service {
    
    public abstract class NamedSubentity : Subentity {
        public string Name
        {
            get; set;
        }

        public NamedSubentity(string name)
        {
            this.Name = name;
        }
    }
}
