//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Service details for ResourceComponentSetup.
///    @author lichong
///    @date 2024/3/26
///
namespace CamstarServiceClient.Service {
    
    public class ResourceComponentSetupDetail : ES_ResourceTxnDetail {
        public IssueControlEnum? IssueControl {
            get; set;
        }
        public ContainerRef FromContainer {
            get; set;
        }
    }
}
