//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Service used to setup the components on a Resource.
///    @author lichong
///    @date 2024/3/26
///
namespace CamstarService.ServiceContent {
    
    public class ResourceComponentSetup : ES_ResourceTxn {
        public ICollection<ResourceComponentSetupDetail> ServiceDetails {
            get; set;
        }
        public ResourceRef Resource {
            get; set;
        }
    }
}
