//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CamstarServiceClient.Service;

///    @Description This CDO holds the changes that are being made to the Object until the user decides to make them permanent.
///    @author lichong
///    @date 2024/3/28
///
namespace CamstarServiceClient.Service {
    
    public abstract class NamedDataObjectChanges : BaseObject {
        public string Name
        {
            get; set;
        }
    }
}
