//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Factory modeling objects that can be uniquely identified by name.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarServiceClient.Service {
    
    public abstract class NamedDataObject : BaseObject {
        public string name
        {
            get; set;
        }

        public NamedDataObject(string name) { 
            this.name = name;
        }
    }
}
