//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Attributes that are common to all CDOs that include revision control (for instances). There are two CDO Definitions for each; a Base Entity and a Revision Entity.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarServiceClient.Service {
    
    public abstract class RevisionedObject : BaseObject {
        public string name
        {
            get; set;
        }
        public string revision
        {
            get; set;
        }
        public bool useROR
        {
            get; set;
        }
        public RevisionedObject(string name, string revision, bool useROR)
        {
            this.name = name;
            this.revision = revision;
            this.useROR = useROR;
        }
    }
}
