//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Sub-Entities are structures that only exist within the context of another CDO. This typically equates to a list-type field within a Modeling CDO.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarServiceClient.Service {
    
    public abstract class Subentity : BaseObject {
    }
}
