//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//    @Description Contains Status Codes for the Container.
//    @author lichong
//    @date 2024/3/25
//
namespace CamstarServiceClient.Service
{
    
    public enum ContainerStatusEnum {
        Deleted = 0,
        Active = 1,
        Closed = 2,
        InTransit = 3,
        IssuedComponent = 4,
    }
}
