//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//    @Description A new enumeration subclass that allows the user to assign an Order State to an Order Status Code.  When OrderState = 1 MfgOrder is active.  When Order State = 2 then Mfg Order is closed.
//    @author lichong
//    @date 2024/3/25
//
namespace CamstarServiceClient.Service {
    
    public enum isOrderStateEnum {
        Open = 1,
        Closed = 2,
    }
}
