//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//    @Description Only non-object data types
//    @author lichong
//    @date 2024/3/25
//
namespace CamstarServiceClient.Service
{
    
    public enum TrivialTypeEnum {
        Object = 5,
        Boolean = 7,
        Decimal = 9,
        Fixed = 3,
        Float = 2,
        Integer = 1,
        String = 4,
        Timestamp = 6,
    }
}
