//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Maint service for Customer.
///    @author lichong
///    @date 2024/3/28
///
namespace CamstarServiceClient.Service {
    
    public class CustomerMaint : NamedDataObjectMaint {
        public CustomerRef ObjectToChange {
            get; set;
        }
        public CustomerChanges ObjectChanges {
            get; set;
        }
    }
}
