//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//    @Description Status codes for the modelling objects (Active, In-Active).
//    @author lichong
//    @date 2024/3/25
//
namespace CamstarService.ServiceContent
{
    
    public enum StatusEnum {
        Active = 1,
        Inactive = 2,
    }
}
