//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description StartDetails describes the attributes of the container about to be started.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarService.ServiceContent {
    
    public class ContainerAttrDetail : ServiceDetails {
       public string Name { get; set; }

        public string AttributeValue { get; set; }

        public TrivialTypeEnum? DataType { get;set; }

        public bool? IsExpression { get; set; }
    }
}
