//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///     @author lichong\n    @date 2024/3/26
///
namespace CamstarService.ServiceContent {
    
    public class ContainerRef : BaseObject{
        public string? Name
        {
            get; set;
        }

        public ContainerRef(string name) { 
            this.Name = name;
        }
    }
}
