//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Services that update either of the two primary shop floor tracking entities (containers and resources).
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarServiceClient.Service {
    
    public abstract class Maintenance : Update {
        public string SyncName
        {
            get; set;
        }
    }
}
