//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description This is simply used to group the sub entities that will be used for shopfloor services.
///    @author lichong
///    @date 2024/3/25
///
namespace CamstarService.ServiceContent {
    
    public abstract class ServiceDetails : ServiceData {
    }
}
